apiVersion: v1
kind: Service
metadata:
  name: kubedoom-service
  namespace: kubedoom
spec:
  type: NodePort
  selector:
    app: kubedoom
  ports:
    - protocol: TCP
      port: 5900
      targetPort: 5900
      nodePort: 32222
